# General configuration
ip_host: 192.168.8.167 # IP address of the camera host
ntp_server: time.apple.com
bitrate: 1000
local_time_frequecy: 10
pan_tilt_frequency: 10

# Camera configuration
cameras:
  camera_1:
    name: c930e
    port: 5000
    usb_port: /dev/video2
    pan_tilt: false
    width: 1280
    height: 720
